// Partially generated by ChatGPT (11/08/2025)

#ifndef SA_H
#define SA_H

#include "headers.h"

class GeneralizedSuffixAutomaton {
public:
    struct Statistics {
        double mid, avg; // median and avg of vector set sizes
        std::vector<int> sizes; // vector set sizes (sorted)
    };

    struct State {
        int len = 0;
        int link = -1;
        std::unordered_map<char, int> next;
        std::vector<uint32_t> ids;
    };
    std::vector<State> st;
        
    // Used for reverse topological sort.
    std::atomic<int>* deg = nullptr;
    std::vector<int>* reverse_next = nullptr;

    // Record which states are affected after inserting a string.
    std::vector<int> affected_states;

    GeneralizedSuffixAutomaton();
    GeneralizedSuffixAutomaton(char* input_file);
    ~GeneralizedSuffixAutomaton();

    // Add a new string with integer ID 'id'. This will index all substrings of s
    // so future queries will return 'id' if a queried substring appears in s.
    // Complexity: O(|s|) amortized.
    void add_string(uint32_t id, const std::string &s);

    // Query which state that pattern p ends.
    // Returns the state id.
    // Complexity: O(|p|).
    int query(const std::string &p) const;

    // The number of states (reflecting space consumption of GSA).
    int size();

    // The number of total ids of states (reflecting total space consumption).
    int size_tot();

    // Clear all data (start fresh).
    void clear();

    // Print the GSA graph.
    void print() const;

    // Statistics of GSA nodes.
    std::vector<Statistics> get_statistics() const;

    // Topological sort of states (for processing in order of links).
    std::vector<int> topo_sort() const;

    // Build reverse edges for the GSA.
    void build_reverse();

    // Dump the index to disk
    void dump(char* output_file);

private:
    int last;
    void sa_extend(char c, uint32_t id);
};

#endif // SA_H
