// Partially generated by ChatGPT (11/08/2025)

#ifndef SA_H
#define SA_H

#include "headers.h"

class GeneralizedSuffixAutomaton {
public:
    struct State {
        int len = 0;
        int link = -1;
        std::unordered_map<char, int> next;
        std::vector<int> ids;
    };
    std::vector<State> st;

    // Record which states are affected after inserting a string.
    std::vector<int> affected_states;

    GeneralizedSuffixAutomaton();

    // Add a new string with integer ID 'id'. This will index all substrings of s
    // so future queries will return 'id' if a queried substring appears in s.
    // Complexity: O(|s|) amortized.
    void add_string(int id, const std::string &s);

    // Query which state that pattern p ends.
    // Returns the state id.
    // Complexity: O(|p|).
    int query(const std::string &p) const;

    // The number of states (reflecting space consumption of GSA).
    int size();

    // The number of total ids of states (reflecting total space consumption).
    int size_tot();

    // Clear all data (start fresh).
    void clear();

    // Print the GSA graph.
    void print() const;

private:
    int last;
    void sa_extend(char c, int id);
};

#endif // SA_H
