// Partially generated by Doubao (28/07/2025)

#include "suffix_tree.h"
#include "headers.h"

int main() {
    std::string s = "ababa";
    std::cout << "Input a string: ";
    std::cin >> s;

    // Create a suffix tree for "ababa"
    SuffixTree st(s);
    
    // Print the tree structure
    st.print();
    
    return 0;
}