// Partially generated by ChatGPT (14/01/2026)

#include <atomic>
#include <cassert>
#include <iostream>
#include <thread>
#include <vector>
#include <unordered_set>
#include <mutex>

#include "mpmc_queue.h"  // include your MPMCQueue implementation

int main() {
    constexpr size_t QUEUE_CAPACITY = 1 << 14;
    constexpr int PRODUCERS = 4;
    constexpr int CONSUMERS = 4;
    constexpr int ITEMS_PER_PRODUCER = 100000;

    MPMCQueue queue(QUEUE_CAPACITY);

    std::atomic<int> produced{0};
    std::atomic<int> consumed{0};

    std::vector<std::thread> threads;

    // Collected results
    std::unordered_set<int> results;
    std::mutex results_mutex;

    // Producers
    for (int p = 0; p < PRODUCERS; ++p) {
        threads.emplace_back([&, p]() {
            int base = p * ITEMS_PER_PRODUCER;
            for (int i = 0; i < ITEMS_PER_PRODUCER; ++i) {
                int value = base + i;
                while (!queue.enqueue(value)) {
                    std::this_thread::yield();
                }
                produced.fetch_add(1, std::memory_order_relaxed);
            }
        });
    }

    // Consumers
    for (int c = 0; c < CONSUMERS; ++c) {
        threads.emplace_back([&]() {
            int value;
            while (consumed.load(std::memory_order_acquire) <
                   PRODUCERS * ITEMS_PER_PRODUCER) {

                if (queue.dequeue(value)) {
                    {
                        std::lock_guard<std::mutex> lock(results_mutex);
                        if (!results.insert(value).second) {
                            std::cerr << "Duplicate value detected: "
                                      << value << std::endl;
                            std::abort();
                        }
                    }
                    consumed.fetch_add(1, std::memory_order_release);
                } else {
                    std::this_thread::yield();
                }
            }
        });
    }

    for (auto& t : threads) {
        t.join();
    }

    // Verification
    int expected = PRODUCERS * ITEMS_PER_PRODUCER;

    std::cout << "Produced: " << produced.load() << std::endl;
    std::cout << "Consumed: " << consumed.load() << std::endl;
    std::cout << "Unique values: " << results.size() << std::endl;

    assert(produced == expected);
    assert(consumed == expected);
    assert(results.size() == static_cast<size_t>(expected));

    std::cout << "MPMC queue test PASSED ✅" << std::endl;
    return 0;
}