// Partially generated by ChatGPT (11/08/2025)

#include "sa.h"
#include <iostream>

int main() {
    GeneralizedSuffixAutomaton gsa;

    // Add some sample strings with IDs 1,2,3
    gsa.add_string(1, "banana");
    gsa.add_string(2, "bandana");
    gsa.add_string(3, "ananas");

    auto print_res = [](const std::string &pat, const std::vector<int> &res){
        std::cout << "Query \"" << pat << "\" -> {";
        for (size_t i=0;i<res.size();++i) {
            std::cout << res[i];
            if (i+1<res.size()) std::cout << ", ";
        }
        std::cout << "}\n";
    };

    print_res("ana", gsa.query("ana"));     // should appear in banana(1) and ananas(3) and bandana(2)
    print_res("ban", gsa.query("ban"));     // banana(1), bandana(2)
    print_res("nana", gsa.query("nana"));   // banana(1), ananas(3)
    print_res("anas", gsa.query("anas"));   // ananas(3)
    print_res("xyz", gsa.query("xyz"));     // empty

    // gsa.print();

    return 0;
}
