// Partially generated by Doubao (01/08/2025)

#include "nsw.h"
#include "headers.h"

// Example usage
int main() {
    // Create an NSW instance
    NSW nsw(16, 200);

    // Initialize with sample vectors
    std::vector<std::vector<float>> vecs = {
        {1.0, 2.0, 3.0},
        {4.0, 5.0, 6.0},
        {7.0, 8.0, 9.0},
        {10.0, 11.0, 12.0},
        {13.0, 14.0, 15.0}
    };

    for (int i = 0; i < vecs.size(); i++) {
        vec.emplace_back(vecs[i]);
        nsw.insert(i);
    }

    // Search for k=2 nearest neighbors
    std::vector<float> query = {2.0, 3.0, 4.0};
    auto neighbors = nsw.searchKNN(query, 2, 10);

    // Print results
    std::cout << "Nearest neighbors to {" << query[0] << ", " << query[1] << ", " << query[2] << "}:\n";
    for (const auto& p : neighbors) {
        std::cout << "Distance: " << nsw.distance(vec[p], query) << ", Index: " << p << "\n";
    }

    return 0;
}