// Partially generated by ChatGPT (11/08/2025)

#include "sa.h"
#include <iostream>

int main() {
    GeneralizedSuffixAutomaton gsa;

    // Add some sample strings with IDs 1,2,3
    std::cout << "Insert 'banana'." << std::endl;
    gsa.add_string(1, "banana");
    std::cout << "Insert 'bandana'." << std::endl;
    gsa.add_string(2, "bandana");
    std::cout << "Insert 'ananas'." << std::endl;
    gsa.add_string(3, "ananas");

    auto print_res = [](const std::string &pat, const std::vector<int> &res){
        std::cout << "Query \"" << pat << "\" -> {";
        for (size_t i=0;i<res.size();++i) {
            std::cout << res[i];
            if (i+1<res.size()) std::cout << ", ";
        }
        std::cout << "}\n";
    };

    print_res("ana", gsa.query("ana"));     // should appear in banana(1) and ananas(3) and bandana(2)
    print_res("ban", gsa.query("ban"));     // banana(1), bandana(2)
    print_res("nana", gsa.query("nana"));   // banana(1), ananas(3)
    print_res("anas", gsa.query("anas"));   // ananas(3)
    print_res("xyz", gsa.query("xyz"));     // empty

    gsa.print();
    std::cout << "Total number of string IDs in GSA: " << gsa.size_tot() << std::endl;

    // Extra tests
    std::cout << "Performing extra tests..." << std::endl;
    gsa.clear();
    std::vector<std::string> data;
    for (int i = 0; i < 1000; i++) {
        std::string s = "";
        for (int j = 0; j < 1000; j++) {
            s += rand() % 26 + 'a';
        }
        data.emplace_back(s);
        gsa.add_string(i, s);
    }
    for (int i = 0; i < 100; i++) {
        std::string s = "";
        for (int j = 0; j < 3; j++) {
            s += rand() % 26 + 'a';
        }
        std::vector<int> std;
        for (int j = 0; j < data.size(); j++) {
            if (data[j].find(s) != std::string::npos) {
                std.emplace_back(j);
            }
        }
        auto res = gsa.query(s);
        assert(std.size() == res.size());
        for (int j = 0; j < std.size(); j++) {
            assert(std[j] == res[j]);
        }
    }
    std::cout << "Extra tests passed!" << std::endl;
    std::cout << "Total number of string IDs in GSA: " << gsa.size_tot() << std::endl;
    std::cout << "Total op count: " << gsa.op_count << std::endl;

    return 0;
}
